-d C:\Users\Armin\Desktop\Isam_slova_konacno\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\Armin\Desktop\Isam_slova_konacno\fpga_project\src\pcf.cst
-cfg C:\Users\Armin\Desktop\Isam_slova_konacno\fpga_project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
